import { copyFile, mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { imageBrowserIconSvg } from '../src/icon.js'

const root = new URL('../', import.meta.url)
const dist = new URL('dist/', root)

await rm(dist, { recursive: true, force: true })
await mkdir(dist, { recursive: true })
await copyFile(new URL('src/backend.js', root), new URL('dist/backend.js', root))

const modelSource = (await readFile(new URL('src/model.js', root), 'utf8'))
  .replace(/^export\s+/gm, '')
const iconSource = (await readFile(new URL('src/icon.js', root), 'utf8'))
  .replace(/^export\s+/gm, '')
const frontendSource = (await readFile(new URL('src/frontend.js', root), 'utf8'))
  .replace(/^import\s*\{[\s\S]*?\}\s*from\s*['"]\.\/model\.js['"]\s*\n/, '')
  .replace(/^import\s*\{ imageBrowserIconSvg \}\s*from\s*['"]\.\/icon\.js['"]\s*\n/, '')
await writeFile(
  new URL('dist/frontend.js', root),
  `// Generated by scripts/build.mjs. Edit src/, not dist/.\n${modelSource}\n${iconSource}\n${frontendSource}`,
  'utf8',
)
await writeFile(new URL('dist/image-browser.svg', root), `${imageBrowserIconSvg(128, 'asset')}\n`, 'utf8')

console.log('Built dist/backend.js, dist/frontend.js, and dist/image-browser.svg')
