import { copyFile, mkdir, readFile, rm, writeFile } from 'node:fs/promises'

const root = new URL('../', import.meta.url)
const dist = new URL('dist/', root)

await rm(dist, { recursive: true, force: true })
await mkdir(dist, { recursive: true })
await copyFile(new URL('src/backend.js', root), new URL('dist/backend.js', root))

const modelSource = (await readFile(new URL('src/model.js', root), 'utf8'))
  .replace(/^export\s+/gm, '')
const frontendSource = (await readFile(new URL('src/frontend.js', root), 'utf8'))
  .replace(/^import\s*\{[\s\S]*?\}\s*from\s*['"]\.\/model\.js['"]\s*\n/, '')
await writeFile(
  new URL('dist/frontend.js', root),
  `// Generated by scripts/build.mjs. Edit src/, not dist/.\n${modelSource}\n${frontendSource}`,
  'utf8',
)

console.log('Built dist/backend.js and dist/frontend.js')
